# Generated by Django 4.2.25 on 2025-11-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_kasports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecarrito',
            name='talla_seleccionada',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gorra',
            name='tallas_disponibles',
            field=models.TextField(blank=True, help_text='Separar tallas con comas. Ej: Única,CH,M,G', null=True),
        ),
        migrations.AddField(
            model_name='ropa',
            name='tallas_disponibles',
            field=models.TextField(blank=True, help_text='Separar tallas con comas. Ej: XS,S,M,L', null=True),
        ),
        migrations.AddField(
            model_name='tenis',
            name='tallas_disponibles',
            field=models.TextField(blank=True, help_text='Separar tallas con comas. Ej: 8,8.5,9', null=True),
        ),
    ]
