# Generated by Django 4.2.25 on 2025-11-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kasports', '0002_detallecarrito_talla_seleccionada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gorra',
            name='talla',
        ),
        migrations.RemoveField(
            model_name='ropa',
            name='talla',
        ),
        migrations.RemoveField(
            model_name='tenis',
            name='talla',
        ),
    ]
